export const SELECTED_MODEL = 'gpt-5';

export const uiStrings = {
    en: {
        title: "AI SQLite Chatbot",
        subtitle: "Ask questions about your local SQLite database.",
        apiLabel: "Step 1: Configure API",
        save: "Save",
        dbLabel: "Step 2: Load your database file (Optional)",
        inputPlaceholder: "Ask a question or type 'generate image of...'",
        inputPlaceholderDisabled: "Ask a question or type 'generate image of...'", // This is not used anymore but kept for consistency
        initialMessage: "Hello! You can start chatting right away. To ask questions about a database, please load a SQLite file.",
        keySaved: "API key saved! Please load a database file.",
        keyMissing: "Please enter a valid API key.",
        dbPrompt: "Please load a database file first to ask questions about your data.",
        dbLoading: "Initializing SQLite engine...",
        dbReading: "Reading file and loading database...",
        dbSuccess: (name, tables) => `Successfully loaded '${name}'. Found tables: ${tables}. You can now ask questions.`,
        dbError: "Error: The file is not a valid SQLite database. Check the developer console (F12) for more details.",
        intentClassification: "Classifying query...",
        sqlGenerating: "AI is generating an SQL query...",
        sqlExecuting: "Executing SQL query...",
        finalAnswer: "Generating a natural language answer...",
        clearChat: "Clear Chat",
        viewSchema: "View Schema",
        hideSchema: "Hide Schema",
        copy: "Copy",
        copied: "Copied!",
        sqlCorrection: "Original query failed. Attempting to self-correct...",
        sqlCorrectionFailed: (sql) => `The self-correction also failed. The last attempted query was:\n${sql}`
    },
    de: {
        title: "KI SQLite Chatbot",
        subtitle: "Stellen Sie Fragen zu Ihrer lokalen SQLite-Datenbank.",
        apiLabel: "Schritt 1: API Konfigurieren",
        save: "Speichern",
        dbLabel: "Schritt 2: Laden Sie Ihre Datenbankdatei (Optional)",
        inputPlaceholder: "Stellen Sie eine Frage oder geben Sie 'Bild von...' ein.",
        inputPlaceholderDisabled: "Stellen Sie eine Frage oder geben Sie 'Bild von...' ein.",
        initialMessage: "Hallo! Sie können sofort mit dem Chatten beginnen. Um Fragen zu einer Datenbank zu stellen, laden Sie bitte eine SQLite-Datei.",
        keySaved: "API-Schlüssel gespeichert! Bitte laden Sie eine Datenbankdatei.",
        keyMissing: "Bitte geben Sie einen gültigen API-Schlüssel ein.",
        dbPrompt: "Bitte laden Sie zuerst eine Datenbankdatei, um Fragen zu Ihren Daten zu stellen.",
        dbLoading: "Initialisiere SQLite-Engine...",
        dbReading: "Lese Datei und lade Datenbank...",
        dbSuccess: (name, tables) => `'${name}' erfolgreich geladen. Gefundene Tabellen: ${tables}. Sie können jetzt Fragen stellen.`,
        dbError: "Fehler: Die Datei ist keine gültige SQLite-Datenbank. Prüfen Sie die Entwicklerkonsole (F12) für Details.",
        intentClassification: "Klassifiziere Anfrage...",
        sqlGenerating: "KI generiert eine SQL-Abfrage...",
        sqlExecuting: "Führe SQL-Abfrage aus...",
        finalAnswer: "Generiere eine natürlichsprachliche Antwort...",
        clearChat: "Chat leeren",
        viewSchema: "Schema anzeigen",
        hideSchema: "Schema ausblenden",
        copy: "Kopieren",
        copied: "Kopiert!",
        sqlCorrection: "Ursprüngliche Abfrage fehlgeschlagen. Versuche, sich selbst zu korrigieren...",
        sqlCorrectionFailed: (sql) => `Die Selbstkorrektur ist ebenfalls fehlgeschlagen. Die letzte versuchte Abfrage war:\n${sql}`
    }
};